post http://localhost:8080/api/disciplina/registrar
Content-Type: application/json

{
    
  "cargaHoraria": 60,
  "codigo": "MAT001",
  "nome": "Matemática",
  "professor": {
    "id": 1
  }

}

POST http://localhost:8080/api/aluno/registrar
Content-Type: application/json

{
    
  "nome": "João Silva",
  "cpf": "125.456.789-00",
  "dataNascimento": "2000-01-01",
  "endereco": "Rua das Flores, 123",
  "telefone": "11987654321",
  "email": "joao.silva@example.com"

}

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "usuario",
    "password": "user123"
}

GET http://localhost:8080/api/aluno/listar
Content-Type: application/json



POST http://localhost:8080/api/turma
Content-Type: application/json

{
    "codigo": "TURMA001",
    "anoLetivo": 2023,
    "professor": { "id": 1 },
    "disciplina": { "id": 1 },
    "turno": "MANHA",
    "periodo": "2023.1",

    "alunos": [
        { "id": 1 }
    ]
}